version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing AWS CLI and dependencies..."
      - apk add --no-cache aws-cli docker

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 396913735068.dkr.ecr.ap-south-1.amazonaws.com
      - echo "Pulling latest image (if exists)..."
      - docker pull 396913735068.dkr.ecr.ap-south-1.amazonaws.com/nodejs-app:latest || true

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t nodejs-app .
      - docker tag nodejs-app:latest 396913735068.dkr.ecr.ap-south-1.amazonaws.com/nodejs-app:latest

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 396913735068.dkr.ecr.ap-south-1.amazonaws.com/nodejs-app:latest
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
  discard-paths: no
